name: Code Coverage Summary
run-name: ${{ github.actor }} is trying to track coverage...
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Code-Coverage-Summary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and collect coverage
        run: npm run test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      - run: echo "🍏 This job's status is ${{ job.status }}."
