name: Code Coverage Summary
run-name: ${{ github.actor }} is trying to track coverage...
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Code-Coverage-Summary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - run: echo "Setting up Node.js version..."
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "Collecting coverage..."
      - run: npm i
      - run: npm run test:coverage
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "Bye..."
